### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by constantinius** [Fred-Leclercq/stac-CF-extention#1]
This STAC extension sounds like a good addition to STAC extension and what we would need in the Open Science Catalog.

Are there any plans to release this extension? Or move it under the official STAC extensions organization?

@m-mohr

**Comment by Fred-Leclercq** [comment]
I'm pleased to see it relocated within the official GitHub repository as an extension. This could potentially attract more attention and, ideally, lead to some collaborative efforts on this extension.

**Comment by m-mohr** [comment]
Great, feel free to send a transfer request to `stac-extensions/cf` and I will happily approve it. If you encounter any issues with the transfer, please let me know. Alternatively, you can add me as an admin here and I'll transfer it. You'll keep your access permissions, of course. @Fred-Leclercq

**Comment by m-mohr** [comment]
Got an invitation, thanks, but I need admin permissions for transfers :-) Currently, I can't access the settings. Alternatively, you can request a transfer yourself.

**Comment by Fred-Leclercq** [comment]
Ah ok, just 'gittered' you - could you have a look? :)

**Comment by m-mohr** [comment]
Have a PR that should be included before the release #2 

Afterwards we can go for the release, I think.

**Comment by Fred-Leclercq** [comment]
Thanks!

**Comment by m-mohr** [comment]
Released!
