### ISSUE TITLE
Add cf:parameter without assets?

### ISSUE THREAD

**Issue by m-mohr** [Fred-Leclercq/stac-CF-extention#4]
Currently, cf:parameter can only be added to the Collection or Item Properties if there are corresponding assets that have a cf:parameter.

I see why this could be useful, but on the other hand we are trying just to express generally what standard_name a Collection belongs to so that it can be used in search, without having assets. Do you think it's reasonable to relax the requirement to have cf:parameter without assets?

@Fred-Leclercq

**Comment by Fred-Leclercq** [comment]
I understand your perspective, but I'm not yet convinced. Is it truly beneficial for it to appear in search results even when there are no assets available?

**Comment by m-mohr** [comment]
In our use case we try to find collections that contain specific standard names, but the assets are in the items. It doesn't makse sense to place thousand assets in a collection just to be able to use the field.
For us it would be good enough to relax this for Collections, I can understand the limitation for items.

Our alternative is to not use this extension and instead use a proprietary field, which is also not ideal.

**Comment by Fred-Leclercq** [comment]
Ok, let's relax this for Collections only.

**Comment by m-mohr** [comment]
Created a PR: #5
